<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a0094bbd-fbc9-433a-ac73-a9f6f04b8b47</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hekucoreapp.Application\Hekucoreapp.Application.csproj" />
    <ProjectReference Include="..\Hekucoreapp.Infrastructure\Hekucoreapp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
